### PR TITLE
PMM-9840 update vendor to can use github.com/prometheus/common/log

### PR DESCRIPTION
**Pull request by YaroslavPodorvanov**
[PMM-9840](https://jira.percona.com/browse/PMM-9840) update vendor to can use github.com/prometheus/common/log

Build: [SUBMODULES-2468](https://github.com/Percona-Lab/pmm-submodules/pull/2468) (previous [SUBMODULES-2443](https://github.com/Percona-Lab/pmm-submodules/pull/2443))

Did simple local test with:
```bash
./azure_metrics_exporter --log.level=info
./azure_metrics_exporter --log.level=error
./azure_metrics_exporter --log.level=undefined_log_level_expect_error_message
```

- [ ] https://github.com/percona/azure_metrics_exporter/pull/4
- [ ] https://github.com/percona/proxysql_exporter/pull/61
- [ ] https://github.com/percona/mysqld_exporter/pull/93

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]

**Comment by BupycHuk** [comment]
please create a FB, so we can see that build is fixed

**Comment by YaroslavPodorvanov** [comment]
> please create a FB, so we can see that build is fixed

@BupycHuk [SUBMODULES-2468](https://github.com/Percona-Lab/pmm-submodules/pull/2468)

**Comment by BupycHuk** [comment]
That FB is failing

**Comment by YaroslavPodorvanov** [comment]
> That FB is failing

@BupycHuk, i remove already deleted branches and restart, thanks for ping me

**Comment by YaroslavPodorvanov** [comment]
@BupycHuk in local i had "vendor" in global `.gitignore` so all new files in "vendor" ignored, i fix that and restart build, waiting

**Review by artemgavrilov — APPROVED** [review]

**Comment by YaroslavPodorvanov** [comment]
@BupycHuk build [/jenkins/pmm2-submodules/detail/PR-2468/4/pipeline/](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-2468/4/pipeline/) is almost complete like one of previous [/jenkins/pmm2-submodules/detail/PR-2466/1/pipeline/95/](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-2466/1/pipeline/95/)

**Pull request merged**
